import type { Metadata } from 'next';
import { Poiret_One, Quicksand } from 'next/font/google';
import './globals.css';

const PoiretOne = Poiret_One({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-poiret-one',
});

const QuicksandFont = Quicksand({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-quicksand',
});

export const metadata: Metadata = {
  title: 'Aaro Viitanen',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <head>
        <meta charSet="UTF-8" />
      </head>
      <html lang="en">
        <body
          className={`${PoiretOne.variable} ${QuicksandFont.variable} antialiased`}
        >
          {children}
        </body>
      </html>
    </>
  );
}
